pkg: delete DMG based daemon installation in pre-install hook (#3882)

diff --git a/nym-vpn-apple/PkgScripts/preinstall b/nym-vpn-apple/PkgScripts/preinstall
--- a/nym-vpn-apple/PkgScripts/preinstall
+++ b/nym-vpn-apple/PkgScripts/preinstall
@@ -6,21 +6,39 @@ INSTALL_DIR=$2
 LOG_DIR=/var/log/nym-vpnd
 NYM_SETUP_BIN="$INSTALL_DIR/NymVPN.app/Contents/MacOS/nym-setup"
 
+PRIVILEGED_HELPER="/Library/PrivilegedHelperTools/net.nymtech.vpn.helper"
+LAUNCH_DAEMON_PLIST="/Library/LaunchDaemons/net.nymtech.vpn.helper.plist"
+SMAPP_SERVICE_VPN_HELPER_SERVICE="system/net.nymtech.vpn.helper"
+
 mkdir -p $LOG_DIR
 chmod 755 $LOG_DIR
 exec > $LOG_DIR/preinstall.log 2>&1
 
 echo "Running preinstall at $(date) with $@"
 
+# Remove the daemon registered by DMG based installation
+if [ -f "$LAUNCH_DAEMON_PLIST" ]; then
+    echo "Remove the daemon registered at $LAUNCH_DAEMON_PLIST"
+    launchctl unload "$LAUNCH_DAEMON_PLIST" || echo "Failed to unload old daemon"
+    rm -f "$LAUNCH_DAEMON_PLIST"
+fi
+
+if [ -f "$PRIVILEGED_HELPER" ]; then
+    echo "Removing privileged helper tool at: $PRIVILEGED_HELPER"
+    rm -f "$PRIVILEGED_HELPER"
+fi
+
+# Remove the daemon registered with SMAppService
+echo "Remove the daemon registered with SMAppService"
+sudo launchctl bootout "$SMAPP_SERVICE_VPN_HELPER_SERVICE" || echo "Failed to bootout old daemon"
+sudo launchctl disable "$SMAPP_SERVICE_VPN_HELPER_SERVICE" || echo "Failed to disable old daemon"
+sleep 1
+
 # Stop the existing daemon
 if [ -f "$NYM_SETUP_BIN" ]; then
     "$NYM_SETUP_BIN" prepare-restart &>/dev/null || \
         echo "Failed to send 'prepare-restart' command to old nym-vpnd"
-elif [ -d "$INSTALL_DIR" ]; then
-    echo "Old installation of nym-vpnd detected"
-    killall nym-vpnd || true
-    sleep 1
 fi
 
 # Kill the GUI before proceeding with the upgrade.
-pkill -x "Nym VPN" && sleep 1 || echo "Unable to kill Nym VPN, not running?"
+pkill -x "NymVPN" && sleep 1 || echo "Unable to kill Nym VPN, not running?"
