pkg(tauri): update linux installer script, drop libfuse2 dep (#3147)

diff --git a/.pkg/linux/install b/.pkg/linux/install
--- a/.pkg/linux/install
+++ b/.pkg/linux/install
@@ -439,36 +439,36 @@ check_system_deps() {
 
   case "$os" in
   *ubuntu* | *debian*)
-    # check for ubuntu version > 22.04 libfuse2 (needed for AppImage)
+    # check for ubuntu version > 22.04 libfuse3 (needed for AppImage)
     fuse_output=$(dpkg --get-selections | grep fuse)
-    if [[ "$fuse_output" != *"libfuse2"* ]]; then
+    if [[ "$fuse_output" != *"libfuse3-3"* ]]; then
       choice=""
-      log "  ${B_GRN}Install$RS required package libfuse2?"
+      log "  ${B_GRN}Install$RS required package libfuse3?"
       prompt="    ${BI_YLW}Y${RS}es (recommended) ${BI_YLW}N${RS}o "
       user_prompt choice "$prompt"
 
       if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
-        sudo apt install -y libfuse2
-        log "   ${B_GRN}Installed$RS libfuse2"
+        sudo apt install -y libfuse3-3
+        log "   ${B_GRN}Installed$RS libfuse3"
       else
-        log "   ${B_YLW}⚠$RS libfuse2 is required for the app to work, install it with:
-        ${I_YLW}sudo apt install libfuse2$RS"
+        log "   ${B_YLW}⚠$RS libfuse3 is required for the app to work, install it with:
+        ${I_YLW}sudo apt install libfuse3-3$RS"
       fi
     fi
     ;;
   *arch* | *manjaro* | *endeavour* | *garuda*)
-    # check if fuse2 is installed (needed for AppImage)
-    if ! pacman -Qk fuse2 &>/dev/null; then
+    # check if fuse3 is installed (needed for AppImage)
+    if ! pacman -Qk fuse3 &>/dev/null; then
       choice=""
-      log "  ${B_GRN}Install$RS required package fuse2?"
+      log "  ${B_GRN}Install$RS required package fuse3?"
       user_prompt choice "    ${BI_YLW}Y${RS}es ${BI_YLW}N${RS}o "
 
       if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
-        sudo pacman -S fuse2 --noconfirm
-        log "   ${B_GRN}Installed$RS fuse2"
+        sudo pacman -S fuse3 --noconfirm
+        log "   ${B_GRN}Installed$RS fuse3"
       else
-        log "   ${B_YLW}⚠$RS fuse2 is required for the app to work, install it with:
-        ${I_YLW}sudo pacman -S fuse2$RS"
+        log "   ${B_YLW}⚠$RS fuse3 is required for the app to work, install it with:
+        ${I_YLW}sudo pacman -S fuse3$RS"
       fi
     fi
     ;;
