Add step to update app version for apps

diff --git a/.github/workflows/build-nym-vpn-apple.yml b/.github/workflows/build-nym-vpn-apple.yml
--- a/.github/workflows/build-nym-vpn-apple.yml
+++ b/.github/workflows/build-nym-vpn-apple.yml
@@ -213,6 +213,30 @@ jobs:
 
           mkdir -p "$SCCACHE_DIR"
 
+      - name: Update core version in app
+        if: ${{ env.RELEASE_TYPE != 'pr' }}
+        run: |
+          set -euo pipefail
+
+          cargo install cargo-get
+
+          # Get version from Cargo.toml workspace
+          LIB_VERSION=$(cargo get workspace.package.version)
+          echo "📦 Core library version: ${LIB_VERSION}"
+
+          # Path to Swift source file
+          app_version_file="nym-vpn-apple/ServicesMutual/Sources/AppVersionProvider/AppVersionProvider.swift"
+
+          # Validate and update
+          if [[ -f "$app_version_file" ]]; then
+            # macOS/BSD sed syntax: -i ''
+            sed -i '' -E 's|(public static let libVersion = ")[^"]*(")|\1'"$LIB_VERSION"'\2|' "$app_version_file"
+            echo "✅ libVersion updated to ${LIB_VERSION} in ${app_version_file}."
+          else
+            echo "❌ Error: AppVersionProvider.swift file not found at ${app_version_file}"
+            exit 1
+          fi
+
       - name: Build core
         working-directory: nym-vpn-apple/scripts
         env:
