Revert "Temp disable input validation"
This reverts commit d9f8f09e68ed275a4a2a74ba450da4f16a0b7be8.

diff --git a/.github/workflows/bump-core-final-release.yml b/.github/workflows/bump-core-final-release.yml
--- a/.github/workflows/bump-core-final-release.yml
+++ b/.github/workflows/bump-core-final-release.yml
@@ -29,12 +29,12 @@ jobs:
       contents: write
       pull-requests: write
     steps:
-      # - name: Validate input
-      #   run: |
-      #     if ! echo "${{ inputs.branch }}" | grep -P '^release/.+$'; then
-      #       echo "::error:: Branch must start with 'release/' (got: ${{ inputs.branch }})"
-      #       exit 1
-      #     fi
+      - name: Validate input
+        run: |
+          if ! echo "${{ inputs.branch }}" | grep -P '^release/.+$'; then
+            echo "::error:: Branch must start with 'release/' (got: ${{ inputs.branch }})"
+            exit 1
+          fi
 
       - name: Configure git
         run: |
