Separate release branch creation and PR bump for develop

diff --git a/.github/workflows/cut-release-branch.yml b/.github/workflows/cut-release-branch.yml
--- a/.github/workflows/cut-release-branch.yml
+++ b/.github/workflows/cut-release-branch.yml
@@ -24,30 +24,77 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  GIT_USER: NYM CI
+  GIT_EMAIL: ci@nymtech.net
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 
 jobs:
-  cut-release-branch:
+  push-release-branch:
     runs-on: ubuntu-latest
-
     permissions:
       contents: write
-      pull-requests: write
-
     steps:
       - name: Configure git
         run: |
-          git config --global user.name "NYM CI"
-          git config --global user.email "ci@nymtech.net"
+          git config --global user.name "${{ env.GIT_USER }}"
+          git config --global user.email "${{ env.GIT_EMAIL }}"
 
       - name: Checkout repo
         uses: actions/checkout@v6
         with:
           ref: develop
           ssh-key: ${{ secrets.CI_RELEASE_DEPLOY_KEY }}
+
+      - name: Install cargo-get
+        uses: baptiste0928/cargo-install@v3
+        with:
+          crate: cargo-get
+
+      - name: Compute release version
+        id: release-version
+        working-directory: nym-vpn-core
+        run: |
+          VERSION=$(cargo get workspace.package.version)
+          # remove -beta suffix
+          RELEASE_VERSION=$(echo "$VERSION" | cut -d '-' -f 1)
+          echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
+
+      - name: Create release branch
+        env:
+          RELEASE_BRANCH: release/${{ steps.release-version.outputs.release_version }}-${{ inputs.release_name }}
+        run: |
+          if git branch -r | grep -qn origin/${{ env.RELEASE_BRANCH }}$; then
+              echo "::error:: ${{ env.RELEASE_BRANCH }} branch already exists but it must not!"
+              exit 1
+          else
+            # create release branch and push it to remote
+            git checkout -b "${{ env.RELEASE_BRANCH }}"
+            if [ '${{ inputs.dry_run }}' == 'true' ]; then
+              echo "Dry run, skipping push to origin/${{ env.RELEASE_BRANCH }}"
+            else
+              git push origin "${{ env.RELEASE_BRANCH }}"
+            fi
+          fi
+
+  bump-develop:
+    runs-on: ubuntu-latest
+    needs: push-release-branch
+    permissions:
+      contents: write
+      pull-requests: write
+    steps:
+      - name: Configure git
+        run: |
+          git config --global user.name "${{ env.GIT_USER }}"
+          git config --global user.email "${{ env.GIT_EMAIL }}"
+
+      - name: Checkout repo
+        uses: actions/checkout@v6
+        with:
+          ref: develop
 
       - name: Install cargo-edit
         uses: baptiste0928/cargo-install@v3
@@ -70,9 +117,6 @@ jobs:
         run: |
           VERSION=$(cargo get workspace.package.version)
 
-          # remove -beta suffix
-          RELEASE_VERSION=$(echo "$VERSION" | cut -d '-' -f 1)
-
           # this would strip -beta suffix
           cargo set-version --bump ${{ inputs.bump_type }}
 
@@ -85,28 +129,7 @@ jobs:
           toml set Cargo.toml workspace.package.version "$BETA_VERSION" > Cargo-patched.toml
           mv Cargo-patched.toml Cargo.toml
 
-          echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
           echo "next_version=$BETA_VERSION" >> "$GITHUB_OUTPUT"
-
-      - name: Create release branch
-        env:
-          RELEASE_BRANCH: release/${{ steps.next-version.outputs.release_version }}-${{ inputs.release_name }}
-        run: |
-          if git branch -r | grep -qn origin/${{ env.RELEASE_BRANCH }}$; then
-              echo "::error:: ${{ env.RELEASE_BRANCH }} branch already exists but it must not!"
-              exit 1
-          fi
-
-          # create release branch and push it to remote
-          git checkout -b "${{ env.RELEASE_BRANCH }}"
-          if [ '${{ inputs.dry_run }}' == 'true' ]; then
-            echo "Dry run, skipping push to origin/${{ env.RELEASE_BRANCH }}"
-          else
-            git push origin "${{ env.RELEASE_BRANCH }}"
-          fi
-
-          # Switch back to develop to apply the remainder of changes
-          git checkout develop
 
       - name: Update nym-vpn-core/Cargo.toml
         working-directory: nym-vpn-core
@@ -131,12 +154,13 @@ jobs:
       - name: Create PR to bump develop to v${{ steps.next-version.outputs.next_version }}
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          BRANCH_NAME: "ci/bump-develop-to-v${{ steps.next-version.outputs.next_version }}"
+          BRANCH_NAME: "ci/bump-develop-v${{ steps.next-version.outputs.next_version }}"
         run: |
           git diff
           if [ '${{ inputs.dry_run }}' == 'true' ]; then
             echo "Dry run, skipping commit and PR creation"
           else
+            git checkout -b "${{ env.BRANCH_NAME }}"
             git commit -a -m "ci: bump develop to v${{ steps.next-version.outputs.next_version }}"
             git push origin "${{ env.BRANCH_NAME }}"
             gh pr create \
