Fix cut-release-branch (#4333)

diff --git a/.github/workflows/cut-release-branch.yml b/.github/workflows/cut-release-branch.yml
--- a/.github/workflows/cut-release-branch.yml
+++ b/.github/workflows/cut-release-branch.yml
@@ -1,8 +1,12 @@
-name: Cut release branch
+name: cut-release-branch
 
 on:
   workflow_dispatch:
     inputs:
+      release_version:
+        description: "Enter release version `YYYY.{n}` (ex: `2026.1`)"
+        type: string
+        required: true
       release_name:
         description: "Enter release name (🍌🍉🥝🍍)"
         type: string
@@ -24,29 +28,75 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  GIT_USER: NYM CI
+  GIT_EMAIL: ci@nymtech.net
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 
 jobs:
-  cut-release-branch:
+  push-release-branch:
     runs-on: ubuntu-latest
-
     permissions:
       contents: write
-      pull-requests: write
-
     steps:
       - name: Configure git
         run: |
-          git config --global user.name "NYM CI"
-          git config --global user.email "ci@nymtech.net"
+          git config --global user.name "${{ env.GIT_USER }}"
+          git config --global user.email "${{ env.GIT_EMAIL }}"
 
       - name: Checkout repo
         uses: actions/checkout@v6
         with:
-          branch: develop
+          ref: develop
+          fetch-depth: 0 # may need this for `git branch -r`
+          ssh-key: ${{ secrets.CI_RELEASE_DEPLOY_KEY }}
+
+      - name: Validate release version
+        run: |
+          if echo "${{ inputs.release_version }}" | grep -P '^[0-9]{4}\.[0-9]{1,2}$'; then
+            echo "Valid release version format"
+          else
+            echo "::error:: Invalid release version format"
+            exit 1
+          fi
+
+      - name: Create release branch
+        env:
+          RELEASE_BRANCH: release/${{ inputs.release_version }}-${{ inputs.release_name }}
+        run: |
+          # match any i.e `yyyy.xx-*`
+          if git branch -r | grep -qn origin/release/${{ inputs.release_version }}-; then
+              echo "::error:: 'release/${{ inputs.release_version }}-*' branch already exists but it must not!"
+              exit 1
+          else
+            # create release branch and push it to remote
+            git checkout -b "${{ env.RELEASE_BRANCH }}"
+            echo "::notice:: Created release branch: ${{ env.RELEASE_BRANCH }}"
+            if [ '${{ inputs.dry_run }}' == 'true' ]; then
+              echo "Dry run, skipping push to origin/${{ env.RELEASE_BRANCH }}"
+            else
+              git push origin "${{ env.RELEASE_BRANCH }}"
+            fi
+          fi
+
+  bump-develop:
+    runs-on: ubuntu-latest
+    needs: push-release-branch
+    permissions:
+      contents: write
+      pull-requests: write
+    steps:
+      - name: Configure git
+        run: |
+          git config --global user.name "${{ env.GIT_USER }}"
+          git config --global user.email "${{ env.GIT_EMAIL }}"
+
+      - name: Checkout repo
+        uses: actions/checkout@v6
+        with:
+          ref: develop
 
       - name: Install cargo-edit
         uses: baptiste0928/cargo-install@v3
@@ -69,41 +119,20 @@ jobs:
         run: |
           VERSION=$(cargo get workspace.package.version)
 
-          # remove -beta suffix
-          RELEASE_VERSION=$(echo "$VERSION" | cut -d '-' -f 1)
-
           # this would strip -beta suffix
-          cargo set-version --bump ${{ inputs.release_type }}
+          cargo set-version --bump ${{ inputs.bump_type }}
 
           # fetch bumped version
           VERSION=$(cargo get workspace.package.version)
 
           # put -beta suffix back
           BETA_VERSION="$VERSION-beta"
-          cargo set-version "$BETA_VERSION"
+          # cargo set-version doesn't allow downgrades, patch toml directly
+          toml set Cargo.toml workspace.package.version "$BETA_VERSION" > Cargo-patched.toml
+          mv Cargo-patched.toml Cargo.toml
 
-          echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
+          echo "::notice:: Next version: $BETA_VERSION"
           echo "next_version=$BETA_VERSION" >> "$GITHUB_OUTPUT"
-
-      - name: Create release branch
-        env:
-          RELEASE_BRANCH: release/${{ steps.next-version.outputs.release_version }}-${{ inputs.release_name }}
-        run: |
-          if git branch -r | grep -qn origin/${{ env.RELEASE_BRANCH }}$; then
-              echo "::error:: ${{ env.RELEASE_BRANCH }} branch already exists but it must not!"
-              exit 1
-          fi
-
-          # create release branch and push it to remote
-          git checkout -b "${{ env.RELEASE_BRANCH }}"
-          if [ '${{ inputs.dry_run }}' == 'true' ]; then
-            echo "Dry run, skipping push to origin/${{ steps.create-release-branch.outputs.branch_name }}"
-          else
-            git push origin "${{ steps.create-release-branch.outputs.branch_name }}"
-          fi
-
-          # Switch back to develop to apply the remainder of changes
-          git checkout develop
 
       - name: Update nym-vpn-core/Cargo.toml
         working-directory: nym-vpn-core
@@ -128,15 +157,16 @@ jobs:
       - name: Create PR to bump develop to v${{ steps.next-version.outputs.next_version }}
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          BRANCH_NAME: "ci/bump-develop-to-v${{ steps.next-version.outputs.next_version }}"
+          BRANCH_NAME: "ci/bump-develop-v${{ steps.next-version.outputs.next_version }}"
         run: |
           git diff
           if [ '${{ inputs.dry_run }}' == 'true' ]; then
             echo "Dry run, skipping commit and PR creation"
           else
+            git checkout -b "${{ env.BRANCH_NAME }}"
             git commit -a -m "ci: bump develop to v${{ steps.next-version.outputs.next_version }}"
             git push origin "${{ env.BRANCH_NAME }}"
             gh pr create \
-                --title "Bump develop to v${{ steps.next-version.outputs.next_version }}" \
-                --body "This PR bumps develop to v${{ steps.next-version.outputs.next_version }}"
+                --title "Bump develop to `v${{ steps.next-version.outputs.next_version }}`" \
+                --body "This PR bumps develop to `v${{ steps.next-version.outputs.next_version }}`"
           fi
