ci: cut-release: use git ls-remote as it's faster than fetching the entire git repo history

diff --git a/.github/workflows/cut-release-branch.yml b/.github/workflows/cut-release-branch.yml
--- a/.github/workflows/cut-release-branch.yml
+++ b/.github/workflows/cut-release-branch.yml
@@ -61,7 +61,6 @@ jobs:
         uses: actions/checkout@v6
         with:
           ref: develop
-          fetch-depth: 0 # may need this for `git branch -r`
           ssh-key: ${{ secrets.CI_RELEASE_DEPLOY_KEY }}
 
       - name: Create release branch
@@ -69,10 +68,9 @@ jobs:
           RELEASE_BRANCH: release/${{ inputs.release_version }}-${{ inputs.release_name }}
         run: |
           # match any i.e `yyyy.xx-*`
-          if git branch -r | grep -qn origin/release/${{ inputs.release_version }}-; then
-              echo "::error:: 'release/${{ inputs.release_version }}-*' branch already exists but it must not!"
-              exit 1
-          else
+          HEAD_COUNT=$(git ls-remote --heads origin 'refs/heads/release/${{ inputs.release_version }}-*' | wc -l | tr -d ' ')
+
+          if [ "$HEAD_COUNT" -eq "0" ]; then
             # create release branch and push it to remote
             git checkout -b "${{ env.RELEASE_BRANCH }}"
             echo "::notice:: Created release branch: ${{ env.RELEASE_BRANCH }}"
@@ -81,6 +79,9 @@ jobs:
             else
               git push origin "${{ env.RELEASE_BRANCH }}"
             fi
+          else
+            echo "::error:: 'release/${{ inputs.release_version }}-*' branch already exists but it must not!"
+            exit 1
           fi
 
   bump-develop:
