Restore build outputs when using cached build

diff --git a/.github/workflows/publish-nym-vpn-android.yml b/.github/workflows/publish-nym-vpn-android.yml
--- a/.github/workflows/publish-nym-vpn-android.yml
+++ b/.github/workflows/publish-nym-vpn-android.yml
@@ -6,14 +6,19 @@ on:
       track:
         type: string
         default: "none"
-      publish-bundle:
+      publish_bundle:
         type: boolean
         default: false
         description: "Publish the app bundle"
-      publish-metadata:
+      publish_metadata:
         description: "Publish app metadata"
         type: boolean
         default: true
+      play_artifact_name:
+        description: "The name of the Play Store artifact (aab)"
+        type: string
+        required: false
+        default: ""
     secrets:
       ANDROID_SERVICE_ACCOUNT_JSON:
         required: true
@@ -62,28 +67,21 @@ jobs:
         uses: actions/download-artifact@v8
         with:
           name: ${{ env.UPLOAD_DIR_ANDROID }}
-          path: dist
-
-      - name: Find artifact file
-        id: find_artifact
-        run: |
-          ARTIFACT_FILE=$(find "${{ github.workspace }}/dist/" -name '*.aab' -type f | head -1)
-          if [ -z "$ARTIFACT_FILE" ]; then
-            echo "::error:: Failed to locate aab artifact"
-            exit 1
-          fi
-          echo "artifact_file=$ARTIFACT_FILE" >> $GITHUB_OUTPUT
-          echo "::notice:: Found artifact for upload: $ARTIFACT_FILE"
 
       - name: Distribute app to fastlane track ${{ inputs.track }} 🚀
         env:
           FASTLANE_OPT_OUT_USAGE: YES
           ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
-          ARTIFACT_FILE: ${{ steps.find_artifact.outputs.artifact_file }}
+          ARTIFACT_FILE: ${{ inputs.play_artifact_name }}
           TRACK: ${{ inputs.track }}
-          SKIP_UPLOAD_BUNDLE: ${{ !inputs.publish-bundle }}
-          SKIP_UPLOAD_METADATA: ${{ !inputs.publish-metadata }}
+          SKIP_UPLOAD_BUNDLE: ${{ !inputs.publish_bundle }}
+          SKIP_UPLOAD_METADATA: ${{ !inputs.publish_metadata }}
         run: |
+          if [ -z "$ARTIFACT_FILE" ]; then
+            echo "::error:: No artifact file specified!"
+            exit 1
+          fi
+
           echo "🚀 Uploading to Google Play Store... (track=$TRACK, skip_bundle=$SKIP_UPLOAD_BUNDLE, skip_metadata=$SKIP_UPLOAD_METADATA)"
 
           bundle exec fastlane supply --aab "$ARTIFACT_FILE" \
diff --git a/.github/workflows/release-release-artifacts.yml b/.github/workflows/release-release-artifacts.yml
--- a/.github/workflows/release-release-artifacts.yml
+++ b/.github/workflows/release-release-artifacts.yml
@@ -40,6 +40,14 @@ on:
         description: "macOS (.pkg + Sparkle)"
         type: boolean
         required: true
+      pkg_installer_name:
+        description: "macOS pkg installer name"
+        type: string
+        required: false
+      fdroid_artifact_name:
+        description: "F-droid artifact name"
+        type: string
+        required: false
     outputs:
       github_release_url:
         value: ${{ jobs.create-release.outputs.github_release_url }}
@@ -231,14 +239,11 @@ jobs:
       - name: Copy artifacts (macOS)
         if: ${{ needs.resolve.outputs.macos == 'true' }}
         env:
-          MACOS_INSTALLER_NAME: ${{ needs.build.outputs.pkg_installer_name }}
+          MACOS_INSTALLER_NAME: ${{ inputs.pkg_installer_name }}
         run: |
           if [ -z "$MACOS_INSTALLER_NAME" ]; then
-            MACOS_INSTALLER_NAME=$(find "${{ env.MACOS_ARTIFACTS }}" -name "*.pkg" -type f -printf "%f" | head -1)
-            if [ -z "$MACOS_INSTALLER_NAME" ]; then
-              echo "::error:: Failed to locate pkg installer"
-              exit 1
-            fi
+            echo "::error:: PKG artifact name is not set!"
+            exit 1
           fi
 
           echo "MACOS_INSTALLER_NAME=$MACOS_INSTALLER_NAME" >> $GITHUB_ENV
@@ -288,14 +293,11 @@ jobs:
       - name: Copy artifacts (Android)
         if: ${{ needs.resolve.outputs.fdroid == 'true' }}
         env:
-          ANDROID_APK: ${{ needs.build.outputs.fdroid_artifact_name }}
+          ANDROID_APK: ${{ inputs.fdroid_artifact_name }}
         run: |
           if [ -z "$ANDROID_APK" ]; then
-            ANDROID_APK=$(find "${{ env.APP_ARTIFACTS_ANDROID_FDROID }}" -name "*.apk" -type f -printf "%f" | head -1)
-            if [ -z "$ANDROID_APK" ]; then
-              echo "::error:: Failed to locate fdroid apk"
-              exit 1
-            fi
+            echo "::error:: APK artifact name is not set!"
+            exit 1
           fi
 
           echo "ANDROID_APK=${ANDROID_APK}" >> $GITHUB_ENV
